apiVersion: v2
name: apiconfig-testing-support
description: Microservice that handles tests about Nodo dei Pagamenti
type: application
version: 0.11.0
appVersion: 0.0.0-11-NOD-494-fix-code
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled

  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle
    condition: oracle.enabled
